<?php
/**
 * Created by PhpStorm.
 * User: alex
 * Date: 08.09.2015
 * Time: 16:21
 */
?>

<p>
    <strong class="label"><?php _e( 'Pay replies:', 'votes_Up-plugin' ); ?></strong>
    <input type="checkbox" name="pay_reply"  value="" <?php echo $pay_reply == 1 ? 'checked="checked"' : '';?> />
</p>
<p>
    <strong class="label"><?php _e( 'Cost:', 'votes_Up-plugin' ); ?></strong>
    <input type="text" name="pay_reply_cred" size="8" value="<?php echo $cost_reply; ?>" />
</p>
<p>
<th scope="row"><?php echo $mycred->plural(); _e(' for reply do not take from:', 'votes_Up-plugin') ?></th>
<br/>
<strong class="label"><?php _e( '', 'votes_Up-plugin' ); ?></strong>

<select multiple size="5" name="group[]">
    <?php
    foreach ($user_status as $values) {
        $selected = (in_array($values,$ar_status))?' selected':'';
        echo "<option value='" . $values . "'$selected>" . $values . "</option>";
    }
    ?>
</select>
</p>
