<?php
/**
 * Created by PhpStorm.
 * User: alex
 * Date: 02.07.2015
 * Time: 13:31
 */
?>
   <!-- <script src="/js/script.js"></script> -->
<!-- Create Form -->
    <div class="wrap">
        <!-- header -->
        <!-- options form -->
        <form name="form1" method="post" action="<?php echo str_replace( '%7E', '~', $_SERVER['REQUEST_URI']); ?>">
            <table class="form-table">

                <tr valign="top">
                    <th scope="row"><?php _e('Добавлять креды за голосование') ?></th>
                <td><input type="checkbox" name="choice"  value="" <?php echo $my_cred_enabled == 1 ? 'checked="checked"' : '';?>/></td>
                </tr>

                <tr valign="top">
                    <th scope="row"><?php _e('Количество добавляемых кредов') ?></th>
                    <td><input type="text" name="voting_up" size="8"
                               value="<?php echo $votes_up_cred; ?>" /></td>
                </tr>

                <tr valign="top">
                    <th scope="row"><?php _e('Плата за создание темы в форуме') ?></th>
                    <td><input type="checkbox" name="Pay_message"  value="" <?php echo $pay_message == 1 ? 'checked="checked"' : '';?> /></td>
                </tr>
                <tr valign="top" id="forums">
                    <th scope="row"><?php _e('Название форума') ?></th>
                    <td>
                        <select id=”forum” name = "forum" value="">
                            <?php
                            global $wpdb;
                            $tbl_posts = $wpdb->prefix . "posts";
                            $query = "SELECT  post_title  FROM $tbl_posts wt
                                          WHERE  wt.post_type = 'forum' and wt.post_status = 'publish'";
                            $res_posts = $wpdb->get_col($query);
                            foreach ($res_posts as $value):?>
                                <option value="<?php echo $value; ?>"
                                    <?php
                                    if ($_POST['forum'] == $value) {
                                        echo "selected";
                                    }
                                    ?>>
                                    <?php
                                    echo $value; ?>
                                </option>
                            <?php endforeach; ?>
                            ?>
                        </select>
                    </td>
                </tr>

                <tr valign="top">
                    <th scope="row"><?php _e('Количество списываемых кредов') ?></th>
                    <td><input type="text" name="pay_vote_cred" size="8" value="<?php echo $pay_vote_cred; ?>" /></td>
                </tr>

                <tr valign="top">
                    <th scope="row"><?php _e('Плата за ответ в теме') ?></th>
                    <td><input type="checkbox" id="Pay_reply" name="Pay_reply"  value="" <?php echo $pay_reply == 1 ? 'checked="checked"' : '';?> /></td>
                </tr>
                <tr valign="top" id="topics" >
                    <th scope="row"><?php _e('Название темы') ?></th>
                    <td>
                        <select name="topics" value="">
                            <?php
                                global $wpdb;
                                $tbl_posts = $wpdb->prefix . "posts";
                                $query = "SELECT  post_title FROM $tbl_posts wt
                                              WHERE  wt.post_type = 'topic'";
                                $res_posts = $wpdb->get_col($query);
                                foreach ($res_posts as $value):?>
                                    <option value="<?php echo $value; ?>"
                                        <?php if ($_POST['topics'] == $value) {
                                            echo "selected";
                                        }?>>
                                        <?php echo $value; ?>
                                    </option>
                                <?php endforeach; ?>

                        </select>
                    </td>
                </tr>
            </table>
            <hr />

            <input type="hidden" name="action" value="update" />
            <input type="hidden" name="page_options" value="voting_up" />

            <p class="submit">
                <input type="submit" name="submit" class="button-primary" value="<?php _e('Save Changes') ?>" />
            </p>

        </form>
    </div>

<!--
Скрипт для сокрытия выпадающего списка с темами, если не выбран чекбокс.
    <script async >
        function toggle() {
            var tr = document.getElementById('topics');
            if(this.checked)
                tr.style.display = 'table-row';
            else
                tr.style.display = 'none';
        }
        document.getElementById('Pay_reply').onchange = toggle;
    </script>
-->


<?php

